spring:
  application:
    name: anastasia-service
logging:
  level:
    org.zalando.logbook: TRACE

logbook:
  strategy: default
  exclude:
    - /actuator/**
    - /swagger-ui/**
    - /v3/api-docs/**
  format:
    style: json
  body:
    max-size: 3000
    filters:
      body: passport
      string: phone,email,name,answer,query,text
      number: latitude,longitude,lat,lon
  headers:
    enabled: false
  logger:
    active: true
